spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mygoodsupporter
    username: mygoodsupporter
    password: mygoodsupporter
    driver-class-name: org.mariadb.jdbc.Driver
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: create

cloud:
  aws:
    stack:
      auto: false

