spring:
  profiles:
    include: aws, local
  datasource:
    url: jdbc:mariadb://localhost:3306/mygoodsupporter
    username: mygoodsupporter
    password: mygoodsupporter
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: io.github.mygoodsupporter.domain
  configuration:
    cache-enabled: true
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
    use-generated-keys: true

cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false

logging:
  level:
    org.springframework: debug
    org.springframework.security: debug
    io.github.mygoodsupporter: debug

cloud:
  aws:
    s3:
      bucket: mygoodsupporter
      region:
      static: ap-northeast-2

