spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mygoodsupporter
    username: mygoodsupporter
    password: mygoodsupporter
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp