create table MEMBER
(
    M_ID VARCHAR(255) not null,
    M_PASSWORD VARCHAR(50),
    M_NAME VARCHAR(255),
    M_PHONE VARCHAR(255),
    M_EMAIL VARCHAR(500),
    M_TYPE VARCHAR(255),
    ENABLED bit default 1,
    AUTHORITY VARCHAR(255) default 'ROLE_MEMBER'
);